/**
 *  Sentinel Software GmbH
 *  Copyright (C) 2022 Andreas Hofmann
 *
 *   This program is free software: you can redistribute it and/or modify
 *   it under the terms of the GNU General Public License as published by
 *   the Free Software Foundation, either version 3 of the License, or
 *   any later version.
 *
 *   This program is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *   GNU General Public License for more details.
 *
 *   You should have received a copy of the GNU General Public License
 *   along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */
/**
 * @addtogroup CharonUDS
 * @{
 * @addtogroup Interface
 * @{
 * @file charon_logo
 * This Module Contains the printed logo for console output.
 * it is more a gimmick to be honest.
 *
 * $Id:  $
 * $URL:  $
 * @}
 * @}
 */
/*****************************************************************************/

#ifndef CHARON_LOGO_H_
#define CHARON_LOGO_H_

/* Includes ******************************************************************/

/* Constants *****************************************************************/

/* Macros ********************************************************************/

#define PRINT_CHARON_LOGO_ON_LOG_OUT()      {           \
    CHARON_INFO("CharonUDS Server Booting up...");      \
    CHARON_INFO("\n\r\n\r\n\r");                        \
    CHARON_INFO("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM");  \
    CHARON_INFO("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM");  \
    CHARON_INFO("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNKd:co0MMMMMMM");  \
    CHARON_INFO("MMMMMMMMMMMMMMMMMMMMMMMMXxlokKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMKl,.    'kNMMMMM");  \
    CHARON_INFO("MMMMMMMMMMMMMMMMMMMMMMMMO.   .,dKMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0'         ,o0WMM");  \
    CHARON_INFO("MMMMMMMMMMMMMMMMMMMMMMMMx.     .dWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWl            lNMM");  \
    CHARON_INFO("MMMMNOdood0WMMMMMMMMMMW0:      lNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN:      ..   cXMMM");  \
    CHARON_INFO("MMM0;.;ll;.oNMMMMMMMWXl.      :NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWl     .oXOdxXMMMM");  \
    CHARON_INFO("MMNc lNMMX;.OMMMMMMMNo.       oWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMO.     .dNMMMMMMM");  \
    CHARON_INFO("MMWk;;OWMK,,KMMMMMMMMWl       cNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWd.      cXMMMMMM");  \
    CHARON_INFO("MMMMNXNMWo.lWMMMMMMMMMk.     .kMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMK,       lNMMMMM");  \
    CHARON_INFO("MMMMMMMXl..xMMMMMMMMMMk.     ,KMMMMMWKXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNc       ;KMMMMM");  \
    CHARON_INFO("MMMMMMMd  .OMMMMMMMMMWl       ,lONMXo:0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXd.     :XMMMMM");  \
    CHARON_INFO("MMMMMMK,  ;XMMMMMMMMMX;         .:;',OMMMMMMMMMMMWWMMMMMMMWNWMMMMMMWWMMWWMMMMMMWNWMMMMMMWWWMWWMMMMMMMMWWMMMMMMMWWMWWWMMMMMMWNWMMMMMMWWMWWWMMWMMMWNWMMMMMMWWMMWWMMMMMMWNWMMMMMMWWMMMMMMMMMMX;      oWMMMM");  \
    CHARON_INFO("MMMMMWl   '0MMMMMMMMMN:        'dc.'kWMMMMMMMMMMMXl:odddoc,';lddddl:kWWx:ldddol;',codddo:oXM0ccodddll:,,:ldddocc0MXo:odddoc,';lodddl:xWNo:loddoc,';lodddl:dWNo:ldddoc;';lodddl:dWMMMMMMMMWx.      ,KMMMM");  \
    CHARON_INFO("MMMMM0'    oWMMMMMMMMMx.      'xo.:KMMMMMMMMMMMMMK,         ..'''.  oMWl      ,cc.       ;XMk.                 .kMX;                 lWX;                 lWN:                 cNMMMMMMMWO'       .kMMMM");  \
    CHARON_INFO("MMMMMx.    .xWMMMMMMMMk.      .''oNMMMMMMMMMMMMMMK;      .:lc:;:od;.oMWo.     ,ko.       ;XMk.                 .kMX:                .lWX:                 lWN:                 cNMMMMMMNd.         lWMMM");  \
    CHARON_INFO("MMMMWl      .oXMMMMMMMd.     ...lNMMMMMMMMMMMMMMMX:     ;ko.    ....dMMd.     ;x,        :XMO'                 'OMNc                .oWNc                .oWNl                .lWMMMMNk,           ;XMMM");  \
    CHARON_INFO("MMMMNc        'dXWMMMNc     .....kMMMMMMMMMMMMMMMWl.   cOc         .kMMk.    .dd',:ld:  .lWMK;     .';:;,:lo;  ;KMWo.    .cd:.;co:  .xMWd.     .;:,,:l,  .xMMd.   .,ol.':cdl. .dMMN0d,             ;XMMM");  \
    CHARON_INFO("MMMMNc          .ckKWO'    ...  '0MMMMMMMMMMMMMMMMx.  'kd.         ;KMMK;    ;0d,'.,xd. .kMMWo.   ;xkl.  'xk' .lNMMk.    .l0l,'...  ,0MMO'    :kl.  .oO; ,OWWO'    'Ox;'..ok' .ldc'.               lWMMM");  \
    CHARON_INFO("MMMMWo             .,,...   ....:xkkkkkkxxxxxxxxxxl.  :O:          ,oooo,   .ox'   ,x:  .:oll;.  ,Ol.    ,xc  .,ccc;.    .xd.       .;::,.   ,Ol    .lk, .,;;,.    ck:   .dl.                     .OMMMM");  \
    CHARON_INFO("MMMMMk.                                               :k:      .            'xc   .ox.           lk,    .dk'             ;k;                 ck,    'xl.          .do.   :x,                     .dWMMMM");  \
    CHARON_INFO("MMMMMK;                                               .oo.   .oo.           lx'   ,Ol           .ck:  .,lkl.            .od.                 ,d;   .ol.           ;k;   .xx.                    .dNMMMMM");  \
    CHARON_INFO("MMMMMWx.                                               .:c;;:ll'           .:;    ,oc.           .;lc:;,':l'            .:'                   ,:;,;:,.            ;:.   .ll'                   'kWMMMMMM");  \
    CHARON_INFO("MMMMMMWd.                                                 ...                                                                                   ...                                          .cKMMMMMMMM");  \
    CHARON_INFO("MMMMMMMWk.                                                                                                                                                                                  ;OWMMMMMMMMM");  \
    CHARON_INFO("MMMMMMMMWKc.                                                                                                                                                                             .cOWMMMMMMMMMMM");  \
    CHARON_INFO("MMMMMMMMMMWKd;.                                                                                                                                                                       .cxXWMMMMMMMMMMMMM");  \
    CHARON_INFO("MMMMMMMMMMMMMWKc                                                                                                                                                                ..':oONMMMMMMMMMMMMMMMMM");  \
    CHARON_INFO("MMMMMMMMMMMMMNd.   .lOkdoollllcccccc::::::;;;;,,,,,,''''''.............................''...'''''',,,,;;;,,;;;;;;,,,,''''''',,''''''''''.............................''',;:cloxk0XNMMMMMMMMMMMMMMMMMMMMM");  \
    CHARON_INFO("MMMMMMMMMMMMK:    .xNWWMMMMMMMMMMMMMMMMMMMMMMWWWWWWWWWWWNNNNNNNNNNNNNNNXXKXXXNXXKKXXXNNNNNNNNNNNWWWWWWWWWWWMMMMMWWWWWWWWWWWWWWWWWWWWWWNNNNXXXXXXXXXXXXXXXXXXKKKKXXXXNNNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM");  \
    CHARON_INFO("MMMMMMMMMMNx.    'OWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM");  \
    CHARON_INFO("MMMMMMMMXx;     ;0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM");  \
    CHARON_INFO("MMMMMMXo.      :XMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM");  \
    CHARON_INFO("MMMMMX:      .lNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM");  \
    CHARON_INFO("MMMMK;      .xNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM");  \
    CHARON_INFO("MMMMO;...,:dKMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM");  \
    CHARON_INFO("MMMMWNXXNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM");  \
    CHARON_INFO("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM");  \
    CHARON_INFO("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM");  \
    CHARON_INFO("\n\r\n\r\n\r");        \
    CHARON_INFO("CharonUDS Server up and running... (C) COPYRIGHT Sentinel Software GmbH");     \
    CHARON_INFO("For more information about our Open Source UDS - Check our website https://www.sentinelsw.de");    \
    }

/* Types *********************************************************************/

/* Interfaces ****************************************************************/

#endif /* CHARON_LOGO_H_ */

/*---************** (C) COPYRIGHT Sentinel Software GmbH *****END OF FILE*---*/


